cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.CartView.as_view(), name='summary'),
    path('shop/', views.ProductListView.as_view(), name='product-list'),
    path('shop/<slug>/', views.ProductDetailView.as_view(), name='product-detail'),
    path('increase-quantity/<pk>/',
         views.IncreaseQuantityView.as_view(), name='increase-quantity'),
    path('decrease-quantity/<pk>/',
         views.DecreaseQuantityView.as_view(), name='decrease-quantity'),
    path('remove-from-cart/<pk>/',
         views.RemoveFromCartView.as_view(), name='remove-from-cart'),
    path('checkout/', views.CheckoutView.as_view(), name='checkout'),
#     path('payment/', views.PaymentView.as_view(), name='payment'),
    path('thank-you/', views.ThankYouView.as_view(), name='thank-you'),
    path('confirm-order/', views.ConfirmOrderView.as_view(), name='confirm-order'),
    path('orders/<pk>/', views.OrderDetailView.as_view(), name='order-detail'),
    path('payment/stripe/', views.StripePaymentView.as_view(), name='payment-stripe'),
    path('config/', views.stripe_config),
    path('create-checkout-session/', views.create_checkout_session, name='checkout_session'),
    path('success/', views.SuccessView.as_view(), name='success'),
    path('cancelled/', views.CancelledView.as_view(), name='cancelled'),
    path('webhooks/stripe/', views.stripe_webhook_view, name='stripe-webhook'),

]

ecom/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
admin.autodiscover()
admin.site.enable_nav_sidebar = False

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('accounts/', include('accounts.urls') ),
]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


admin.site.site_header = 'ecom admin'
admin.site.site_title = 'ecom admin'
admin.site.site_url = 'http://ecom.com/'
admin.site.index_title = 'ecom administration'

main/urls.py
from django.urls import path
from . import views
from cart.views import ProductListView

app_name = 'main'

urlpatterns = [
    path('', ProductListView.as_view(), name='home'),
    path('contact/', views.ContactView.as_view(), name='contact'),
    path('profile/', views.ProfileView.as_view(), name='profile')
]

main/models.py
from django.db import models
from django.db.models.signals import post_save
from django.contrib.auth import get_user_model

User = get_user_model()


class Customer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    stripe_customer_id = models.CharField(max_length=100, blank=True, null=True)

    def __str__(self):
        return self.user.email


def post_save_user_receiver(sender, instance, created, **kwargs):
    if created:
        Customer.objects.create(user=instance)


post_save.connect(post_save_user_receiver, sender=User)

main/forms.py
from django import forms


class ContactForm(forms.Form):
    name = forms.CharField(max_length=100, widget=forms.TextInput(attrs={
        'placeholder': "Your name"
    }))
    email = forms.EmailField(widget=forms.TextInput(attrs={
        'placeholder': "Your e-mail"
    }))
    message = forms.CharField(widget=forms.Textarea(attrs={
        'placeholder': 'Your message'
    }))

main/views.py
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.mail import send_mail
from django.shortcuts import reverse
from django.views import generic
from cart.models import Order
from .forms import ContactForm


class ProfileView(LoginRequiredMixin, generic.TemplateView):
    template_name = 'main/profile.html'

    def get_context_data(self, **kwargs):
        context = super(ProfileView, self).get_context_data(**kwargs)
        context.update({
            "orders": Order.objects.filter(user=self.request.user, ordered=True)
        })
        return context


class HomeView(generic.TemplateView):
    template_name = 'main/home.html'


class ContactView(generic.FormView):
    form_class = ContactForm
    template_name = 'main/contact.html'

    def get_success_url(self):
        return reverse("main:contact")

    def form_valid(self, form):
        messages.info(
            self.request, "Thanks for getting in touch. We have received your message.")
        name = form.cleaned_data.get('name')
        email = form.cleaned_data.get('email')
        message = form.cleaned_data.get('message')

        full_message = f"""
            Received message below from {name}, {email}
            ________________________


            {message}
            """
        send_mail(
            subject="Received contact form submission",
            message=full_message,
            from_email=settings.DEFAULT_FROM_EMAIL,
            recipient_list=[settings.NOTIFY_EMAIL]
        )
        return super(ContactView, self).form_valid(form)

templates/main/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>SPATIME</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/message.css' %}">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<style>

</style>
<body>
{% include 'main\navbar.html' %}
{% include 'main\messages.html' %}
<div style="margin-top: 3%">
    {% block content %}
    {% endblock %}
    
</div>

<script src="{% static 'js/jquery-3.5.1.slim.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/bootstrap.bundle.min.js' %}" type="text/javascript"></script>
<script type="application/javascript">
    $(document).ready(function(){
        $('#exampleModal').modal({show:true});
    });
</script>
<style>
    .navbar-nav {
    display: inline-block;
    }

    .navbar-nav>li {
    display: inline-block;
    }
    
    .avatar {
        width: 5rem;
        height: 5rem;
        border-radius: 50%;
    }
    .avatar-small {
        width: 2rem;
        height: 2rem;
        border-radius: 50%;
    }
    </style>
</body>
</html>

templates/main/contact.html
{% extends "main/base.html" %}
{% load crispy_forms_tags %}

{% block content %}

<div class="bg-light py-3">
    <div class="container">
        <div class="row">
            <div class="col-md-12 mb-0">
                <a href="{% url 'main:home' %}">Home</a>
                <span class="mx-2 mb-0">/</span>
                <strong class="text-black">Contact</strong>
            </div>
        </div>
    </div>
</div>

<div class="site-section">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-7">
                <h2 class="h3 mb-3 text-black">Get in touch</h2>
            </div>
            <div class="col-md-7">
                <form method="POST">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <input type="submit" class="btn btn-primary btn-lg btn-block" value="Submit message" />
                </form>
            </div>
        </div>
    </div>
</div>


{% endblock content %}

templates/main/home.html
{% extends 'main/base.html' %}
{% load static %}

{% block content %}

  <div class="container">
    <div class="jumbotron text-center ">
      <h1 class="display-4 text-primary">Lesson hubs</h1>
    </div>

    <div class="row">
      <div class="col mb-3">
        <div class="card border-primary">
          <div class="card-body text-primary">
            <h5 class="card-title">Video lessons app</h5>
            <p class="card-text">Manages all your video lessons</p>
          </div>
        </div>
        </div>
    </div>

    <div class="row">
      
      <div class="col-lg-6 col-md-6 col-sm-12 mb-3">
        <div class="card border-primary">
          <div class="card-body text-primary">
            <h5 class="card-title">Simple</h5>
            <p class="card-text">Really simple to use</p>
          </div>
        </div>
        </div>

      <div class="col-lg-6 col-md-6 col-sm-12">
        <div class="card border-primary">
          <div class="card-body text-primary">
            <h5 class="card-title">Economical</h5>
            <p class="card-text">Save your mnoney</p>
          </div>
        </div>
        </div>


      </div>

      
    </div> <!-- container row -->
    
  </div> <!-- container main -->
  
</div>
{% endblock %}

templates/main/messages.html
{% if messages %}

{% for message in messages %}
<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog h-100 d-flex flex-column justify-content-center my-0" role="document">

    <div class="modal-content {{ message.tags }}">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">{{ message }}</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    </div>
    <!-- modal-content -->

  </div>
</div>
<!-- Modal -->
{% endfor %}
{% endif %}

templates/main/navbar.html
{% load static %}
{% load cart_template_tags %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      
      <li class="nav-item">
        <a class="nav-link" href="{% url 'main:contact' %}">contact</a>
      </li>
      
      

      {% if user.is_authenticated %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'main:home' %}">shop</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'main:profile' %}">Profile 
        </a>
      </li>
      <li>
        <a href="{% url 'cart:summary' %}" class="site-cart">
            <span><i class="fas fa-shopping-cart">cart</i></span>
            <span class="count">{{ request|cart_item_count }}</span>
        </a>
    </li>
      <li class="nav-item">
          <form
          action="{% url 'logout' %}" 
          alt='djangonautic'
          method="post">
              {% csrf_token %}
              <button class="btn btn-outline-secondary" type="submit">Logout</button>
          </form>
      </li>
      
      {% else %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'main:home' %}">shop</a>
      </li>
      <li>
        <a href="{% url 'cart:summary' %}" class="site-cart">
            <span><i class="fas fa-shopping-cart">cart</i></span>
            <span class="count">{{ request|cart_item_count }}</span>
        </a>
      </li>
      <li class="nav-item">
        <a class="navbar-brand" href="{% url 'login' %}">Login</a>
      </li>
      {% endif %}
      
    </ul>
    <a class="navbar-brand mt-n3" href="">Logo</a>
  </div>
</nav>

templates/main/profile.html
{% extends "main/base.html" %}

{% block content %}

<div class="site-section">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <h2 class="text-black">Your profile</h2>
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">
                            {{ request.user.email }}
                            <a href="{% url 'logout' %}">
                                <small class="float-right">Logout</small></a>
                        </h5>
                        <hr />
                        <h5 class="card-title">Your orders</h5>
                        <div class="site-blocks-table">
                            <table class="table">
                                <thead>
                                    <tr>
                                        <th>Reference No.</th>
                                        <th>Date</th>
                                        <th>Amount</th>
                                        <th>Payment Status</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for order in orders %}
                                    <tr>
                                        <td><a href="">#{{ order.reference_number }}</a></td>
                                        <td>{{ order.ordered_date }}</td>
                                        <td>${{ order.get_total }}</td>
                                        <td>{% if order.ordered %}Paid{% else %}Not paid{% endif %}</td>
                                    </tr>
                                    {% empty %}
                                    <tr>
                                        <td colspan="4">You haven't made any orders</td>
                                    </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}